# Environment
env=qa

# Appium server
appium.server.url=http://127.0.0.1:4723/wd/hub

# Timeouts
implicit.wait=10
explicit.wait=20

# Reporting
report.path=reports/extent/

# App details (placeholders)
app.package=com.vakeelsaabclient
app.activity=.MainActivity

# Default device
default.device=emulator-5554

# App path (place your APK under repo `apps/` or set an absolute path)
app=apps/app-debug.apk
noReset=false
fullReset=true
platformName=Android
automationName=UiAutomator2
deviceName=emulator-5554
platformVersion=13.0
appiumURL=http://127.0.0.1:4723
